// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nntnqlciqswjclcvtulk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5udG5xbGNpcXN3amNsY3Z0dWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDI4NjYsImV4cCI6MjA3NDE3ODg2Nn0.1Xl2UGd_RROsvhicCzxlxhw3Ihl6z32Nu37rbVXTEjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});